### ISSUE TITLE
zmf_swmgmt_csi_query not working

### ISSUE THREAD

**Issue by adn1107** [IBM/ibm_zosmf#21]
```
- name: Query a CSI data set
  ansible.builtin.include_role:
    name: ibm.ibm_zosmf.zmf_swmgmt_csi_query
  vars: 
    software_instance_name: '{{ item.name }}'
    system_nickname: '{{item.system}}'
    zones: '"ALLTZONES"'
    entries: '"SYSMOD"'
    csi_query_response_file: '{{ playbook_dir }}/playbook_output/{{ software_instance_name }}-CSI_DS.json'
```

```
fatal: [zos_host]: FAILED! => changed=false 
  msg: 'CSI Query failure details: {''reason'': ''2'', ''messages'': [''The request could not be completed because an error occurred. Error: "java.lang.String incompatible with com.ibm.json.java.JSONArray"'']} '
```
